export default [
    'Abercrombie & Fitch',
    'Ace Hardware',
    'Adobe',
    'Coors Beer and More',
    'Advance Auto Parts',
    'Aetna',
    'Airborne',
    'Airgas',
    'Alaska Air',
    'Allied Waste Industries',
    'Amazon',
    'AMC',
    'Amnesty International',
    'American Eagle',
    'American Express',
    'American Greetings Corporation',
    'AnnTaylor',
    'American Government',
    "Your Mom's House", 
    'AOL',
    'Apple',
    'AT&T',
    'AutoZone',
    'Avon',
    'LuLuLemon',
    'Herbalife',
    'Mary Kay',
    'Lularoe',
    'Amway',
    'Doterra',
    'Tupperware',
    'Bank of America',
    'Barnes & Noble',
    'Bed Bath & Beyond',
    'Berkshire Hathaway',
    'Best Buy Co',
    'Bethlehem Steel',
    'Big Lots',
    "BJ's Wholesale Club",
    'Boeing',
    'Boston Scientific Corporation',
    'Bristol-Myers Squibb',
    'Brown Shoe Company',
    'Burlington Coat Factory Warehouse',
    'Campbell Soup Co',
    'Capital One',
    'CVS',
    "Casey's General Stores.",
    'Caterpillar',
    'Charles Schwab Corp',
    'Charming Shoppes',
    "Claire's",
    'Chiquita Brands International',
    'Dole',
    'Chubb Corp',
    'Cinergy Corp',
    'Circuit City',
    'Coca-Cola',
    'Unilever',
    'Colgate-Palmolive',
    'Comcast',
    'Comdisco',
    'SnOasis',
    'Comfort Systems USA',
    'Constellation Brands',
    'Constellation Emergy Group',
    'Corn Products International',
    'Costco',
    'Cox Communications',
    'Crown Cork & Seal Co.',
    'Dell',
    'Delta Air Lines',
    "Dillard's.",
    'Dollar General',
    'Dollar Tree',
    "Domino's",
    "Dreyer's Grand Ice Cream",
    'E*Trade Group',
    'Kodak',
    'Ecolab',
    'Electronic Arts',
    'Energizer',
    'Engelhard Corporation',
    'Enron',
    'Equifax',
    'Estee Lauder',
    'ExxonMobil',
    'Family Dollar',
    'Farmland Industries',
    'FederalEx',
    'Flowers Foods',
    'Foamex International',
    'Foot Locker',
    'Footstar',
    'Gap',
    'TV Guide',
    'GenCorp',
    'General Electric',
    'General Mills',
    'General Motors',
    'Gillette',
    'Goldman Sachs',
    'Goodrich Corporation',
    'Goodyear Tire & Rubber Company',
    'H&R Block',
    'Heinz',
    'Harley-Davidson',
    'Hasbro',
    'Hercules',
    'Hewlett-Packard',
    'Hilton Hotels',
    'Home Depot',
    'Humana',
    'Imperial Sugar Company',
    'International Paper Co',
    'Interstate Bakeries Corporation',
    'IBM',
    'International Flavors & Fragrances',
    'J.C. Penny',
    'J.P. Morgan Chase',
    'Jack In The Box',
    'Johnson & Johnson',
    'Kellogg',
    'K-Mart',
    'Knight-Ridder',
    "Kohl's.",
    'Kroger Co',
    "Lands' End.",
    'La-Z-Boy',
    'Legg Pantyhose',
    'Lehman Brothers',
    'Levi',
    "Linens 'n Things.",
    'Lockheed Martin',
    'Loews',
    'Manpower',
    'Marriott Hotels',
    'Marsh Supermarkets',
    'Playboy Magazine',
    'Maxim Magazine',
    'Maytag',
    "McDonald's",
    "Men's Wearhouse--you're gonna like the way you look.",
    'Merck',
    'Merrill Lynch.',
    'Metals USA',
    'Michaels',
    'Microsoft',
    'MoistCo!',
    'Motorola',
    'National Oilwell',
    'National Rural Utilities Cooperative Finance Corporation',
    'National Service Industries',
    'Neiman Marcus',
    'New York Times',
    'Rubbermaid',
    'Nike',
    'Nordstrom',
    'Ocean Energy',
    'OfficeMax',
    'Oglethorpe Power Corp',
    'Ohio Casualty Corp',
    'Oracle',
    'Oshkosh',
    'Outback Steakhouse',
    'Packaging Corp. of America',
    'Pantry',
    'Paychex',
    'Payless Shoesource',
    'Pep Boys Manny, Moe, & Jack',
    'Pepsi',
    "Elmer's Glue",
    'Petco',
    'Pfizer',
    'Pier 1 Imports',
    'Popular',
    'Gay Pride International',
    'Procter & Gamble',
    'Progressive Corporation',
    'Quantum Corp',
    'Quest Diagnostics',
    'Radio Shack Corporation',
    'Raytheon',
    "Reader's Digest.",
    'Reebok',
    'Rent A Center',
    'Sabre Holdings Corp',
    'Safeco Corp',
    'Safeway',
    'Saks',
    'Sara Lee',
    'Scholastic',
    'Scotts Company',
    'Sealed Air Corp',
    'Sears',
    'ServiceMaster Co',
    'Sherwin-Williams',
    'Smurfit-Stone Container Corp',
    'Snap-On',
    'Solutia',
    'Sonic Automotive',
    'Southwest Airlines',
    'Sports Authority',
    'Stanley Works',
    'Staples',
    'Starbucks',
    'Target',
    'Tech Data Corporation',
    'Texas Instruments',
    "Tiffany's",
    "Toys 'R' Us",
    'Trump Hotels & Casino Resorts',
    'Tyson Foods',
    'UPS',
    'Universal Studios',
    'US Airways',
    'USA Interactive',
    'Value City Department Stores',
    "Walgreen's",
    'Wal-Mart',
    'Disney',
    'Washington Post',
    'Waste Management',
    'Wells Fargo',
    "Wendy's",
    'Whirlpool',
    'Whole Foods',
    'Williams Sonoma',
    'Xerox',
    'XO Communications',
    'Yellow Corporation',
    'Yum Brands',
    "Zendaya's",
    'Zions Bancorporation',
    'BookBub',
    'Kesher Afterschool',
    'MassDOT',
    'MBTA',
    'Voltus',
    'Toast',
    'JB Psychiatry',
    'Weyland-Yutani Corporation',
    'Umbrella Corporation',
    'Soylent Corporation',
    'Cyberdyne Systems',
    'InGen',
    'Initech',
    'Buy n Large',
    'KardashianPutin Global Enterprises',
    'Yeezy Inc',
    'Wonka Industries',
    'Monsters, Inc',
    'Krusty Krab',
    'Los Pollos Hermanos',
    'Bluth Company',
    'MOM Corp',
    'Daddy House and Inn',
    'Office of Senator, Speaker, and Supreme Leader Michelle Obama',
    'Liberty University', 
    'A small university across the river', 
    'Unemployed',
    'Y-ENBY-CA', 
    'Supreme Court', 
    'Underwater', 
    'Waterworks Museum and Condos', 
    'BBC Radio', 
    'CSPAN', 
    'Your Butt', 
    'The Set of Survivor', 
    '25 Forest Hills Street, Jamaica Plain, MA, 02130',
    'TD Garden', 
    'BackBar',
    'The Somerville Public Library', 
    'Local Nursing Home', 
    'Halal Cart', 
    'Yankee Candle', 
    'Pelaton', 
    'Feet of Clay Pottery Studio and Creative Space', 
    'Planned Parenthood', 
    'Lola (formerly known as The Sisterhood of the Traveling Tampon)',
    'Idle Hands Brewery', 
    'Full-Stack Engineering Co.', 
    'City of Akron', 
    'The Prince Charles Estate', 
    'The Air, Land, and Water Institute of Saving the Earth',
    'The Church of Jesus Christ, Astrologer', 
    'PETA', 
    'First Baptist Chestnut Hill', 
    'Orphan Industries', 
];
