export default [
    'Abercrombie & Fitch',
    'Ace Hardware',
    'Adobe',
    'Coors',
    'Advance Auto Parts',
    'Aetna',
    'Airborne',
    'Airgas',
    'Alaska Air',
    'Allied Waste Industries',
    'Amazon',
    'AMC',
    'American Eagle',
    'American Express',
    'American Greetings Corporation',
    'AnnTaylor',
    'AOL',
    'Apple',
    'AT&T',
    'AutoZone',
    'Avon',
    'Bank of America',
    'Barnes & Noble',
    'Bed Bath & Beyond',
    'Berkshire Hathaway',
    'Best Buy Co',
    'Bethlehem Steel',
    'Big Lots',
    "BJ's Wholesale Club",
    'Boeing',
    'BorgWarner',
    'Boston Scientific Corporation',
    'Bristol-Myers Squibb',
    'Broadwing',
    'Brown Shoe Company',
    'Burlington Coat Factory Warehouse',,
    'Campbell Soup Co',
    'Capital One',
    'CVS',
    "Casey's General Stores.",
    'Caterpillar',
    'Champion Enterprises',
    'Charles Schwab Corp',
    'Charming Shoppes',
    'Chiquita Brands International',
    'Chubb Corp',
    'Cinergy Corp',
    'Circuit City',
    'Cisco Systems',
    'Citigroup,',
    'Clear Channel',
    'Clorox',
    'Coca-Cola',
    'Colgate-Palmolive',
    'Comcast',
    'Comdisco',
    'Comerica',
    'Comfort Systems USA',
    'Constellation Brands',
    'Constellation Emergy Group',
    'Corn Products International',
    'Costco',
    'Cox Communications',
    'Crown Cork & Seal Co.',
    'Dell',
    'Delta Air Lines',
    "Dillard's.",
    'Dollar General',
    'Dollar Tree',
    "Domino's",
    "Dreyer's Grand Ice Cream",
    'Dynegy',
    'E*Trade Group',
    'E.W. Scripps Company',
    'Kodak',
    'Ecolab',
    'Electronic Arts',
    'Eli Lilly',
    'Energizer',
    'Engelhard Corporation',
    'Enron',
    'Equifax',
    'Estee Lauder',
    'ExxonMobil',
    'Family Dollar',
    'Farmland Industries',
    'FederalEx',
    'Flowers Foods',
    'Foamex International',
    'Foot Locker',
    'Footstar',
    'Ford',
    'Forest Laboratories',
    'Fortune Brands',
    'Gap',
    'Gateway',
    'TV Guide',
    'GenCorp',
    'General Electric',
    'General Mills',
    'General Motors',
    'Gillette',
    'Goldman Sachs',
    'Goodrich Corporation',
    'Goodyear Tire & Rubber Company',
    'H&R Block',
    'Heinz',
    'Harley-Davidson',
    'Hasbro',
    'Hercules',
    'Herman Miller',
    'Hershey',
    'Hewlett-Packard',
    'Hilton Hotels',
    'Home Depot',
    'Humana',
    'Imperial Sugar Company',
    'Intel',
    'International Paper Co',
    'Interstate Bakeries Corporation',
    'IBM',
    'International Flavors & Fragrances',
    'J.C. Penny',
    'J.P. Morgan Chase',
    'Jack In The Box',
    'Johnson & Johnson',
    'Johnson Controls',
    'Kellogg',
    'K-Mart',
    'Knight-Ridder',
    "Kohl's.",
    'Kroger Co',
    "Lands' End.",
    'La-Z-Boy',
    'Lear Jet',
    'Legg Pantyhose',
    'Lehman Brothers',
    'Levi',
    "Linens 'n Things.",
    'Liz Claiborne',
    'Lockheed Martin',
    'Loews',
    'Mail-Well',
    'Manpower',
    'Marriott Hotels',
    'Marsh Supermarkets',
    'Maxim Magazine',
    'Maytag',
    "McDonald's",
    "Men's Wearhouse--you're gonna like the way you look.",
    'Merck',
    'Merrill Lynch.',
    'Metals USA',
    'MetLife',
    'Michaels',
    'Microsoft',
    'Milacron',
    'MoistCo!',
    'Motorola',
    'National Oilwell',
    'National Rural Utilities Cooperative Finance Corporation',
    'National Service Industries',
    'Neiman Marcus',
    'New York Times',
    'Rubbermaid',
    'Nike',
    'Nordstrom',
    'Norfolk Southern Corporation',
    'NSTAR',
    'Nvidia',
    'Ocean Energy',
    'Office Depot',
    'OfficeMax',
    'Oglethorpe Power Corp',
    'Ohio Casualty Corp',
    'Oracle',
    'Oshkosh',
    'Outback Steakhouse',
    'Packaging Corp. of America',
    'Pantry',
    'Paychex',
    'Payless Shoesource',
    'Pep Boys Manny, Moe & Jack',
    'Pepsi',
    "Elmer's Glue",
    'Petco',
    'PETsMART',
    'Pfizer',
    'Philip Morris',
    'Pier 1 Imports',
    'Polaris Industries',
    'Polo Ralph Lauren Corp',
    'PolyOne Corp',
    'Popular',
    'Potlatch Corp',
    'PPL Corp',
    'Pride International',
    'Primedia',
    'Procter & Gamble',
    'Progressive Corporation',
    'Protective Life Corp',
    'Publix Super Markets',
    'Quantum Corp',
    'Quest Diagnostics',
    'Questar',
    'Quintiles Transnational',
    'Qwest Communications',
    'Radio Shack Corporation',
    'Raytheon',
    "Reader's Digest.",
    'Reebok',
    'Rent A Center',
    'Revlon',
    'Rite Aid Corp',
    'Riverwood Holding',
    'Rock-Tenn Co',
    'Sabre Holdings Corp',
    'Safeco Corp',
    'Safeway',
    'Saks',
    'Sara Lee',
    'Scholastic',
    'Scotts Company',
    'Sealed Air Corp',
    'Sears',
    'ServiceMaster Co',
    'Sherwin-Williams',
    'Smurfit-Stone Container Corp',
    'Snap-On',
    'Solutia',
    'Sonic Automotive',
    'Southwest Airlines',
    'Sports Authority',
    'Stanley Works',
    'Staples',
    'Starbucks',
    'Target',
    'Tech Data Corporation',
    'Texas Instruments',
    "Tiffany's",
    "Toys 'R' Us",
    'Trump Hotels & Casino Resorts',
    'Tyson Foods',
    'UPS',
    'Universal Studios',
    'US Airways',
    'USA Interactive',
    'Value City Department Stores',
    'Wakenhut Corporation',
    "Walgreen's",
    'Wal-Mart',
    'Disney',
    'Washington Post',
    'Waste Management',
    'Wells Fargo',
    "Wendy's",
    'Whirlpool',
    'Whole Foods',
    'Williams Sonoma',
    'Xerox',
    'XO Communications',
    'Yellow Corporation',
    'Yum Brands',
    "Zale's",
    'Zions Bancorporation',
    'BookBub',
    'Kesher Afterschool',
    'MassDOT',
    'MBTA',
    'Voltus',
    'Weyland-Yutani Corporation',
    'Umbrella Corporation',
    'Soylent Corporation',
    'Cyberdyne Systems',
    'InGen',
    'Initech',
    'Buy n Large',
    'KardashianPutin Global Enterprises',
    'Yeezy Inc',
    'Wonka Industries',
    'Monsters, Inc',
    'Krusty Krab',
    'Los Pollos Hermanos',
    'Bluth Company',
    'MOM Corp'
];
