export default [
    '3M Company',
    'Abbott Laboratories',
    'Abercrombie & Fitch Co',
    'Ace Hardware Corporation',
    'ACT Manufacturing',
    'Adams Resources & Energy',
    'Administaff',
    'Adobe Systems',
    'Adolph Coors Company',
    'Advance Auto Parts',
    'Advanced Micro Devices',
    'Aetna',
    'Affiliated Computer Services',
    'Agilent Technologies',
    'Agway',
    'Apartment Investment and Management Company',
    'Air Products and Chemicals',
    'Airborne',
    'Airgas',
    'AK Steel Holding Corporation',
    'Alaska Air Group',
    'Allied Waste Industries',
    'The Allstate Corporation',
    'Amazon',
    'AMC Entertainment',
    'American Power Conversion Corporation',
    'American Axle & Manufacturing Holdings',
    'American Eagle Outfitters',
    'American Electric Power Company',
    'American Express Company',
    'American Greetings Corporation',
    'American Water Works Company',
    'Ames Department Stores',
    'Amtran',
    'Analog Devices',
    'Anheuser-Busch Companies',
    'AnnTaylor',
    'Anthem',
    'AOL Time Warner',
    'Aon Corporation',
    'Apache Corporation',
    'Apple Computer',
    'Aquila',
    'Arch Coal',
    'Arkansas Best Corporation',
    'Armstrong Holdings',
    'AT&T Corp',
    'Atmos Energy Corporation',
    'Audiovox Corporation',
    'Autoliv',
    'Automatic Data Processing',
    'AutoNation',
    'AutoZone',
    'Avaya',
    'Avery Dennison Corporation',
    'Avista Corporation',
    'Avnet',
    'Avon Products',
    'Baker Hughes',
    'Ball Corporation',
    'Bank of America Corporation',
    'The Bank of New York Company',
    'Bank One Corporation',
    'Banknorth Group',
    'Banta Corporation',
    'Barnes & Noble',
    'Bausch & Lomb',
    'Baxter International',
    'BB&T Corporation',
    'The Bear Stearns Companies',
    'Beazer Homes USA',
    'Beckman Coulter',
    'Becton, Dickinson and Company',
    'Bed Bath & Beyond',
    'Belk',
    'Bell Microproducts',
    'BellSouth Corporation',
    'Belo Corp',
    'Bemis Company',
    'Benchmark Electronics',
    'Berkshire Hathaway',
    'Best Buy Co',
    'Bethlehem Steel Corporation',
    'Beverly Enterprises',
    'Big Lots',
    'BJ Services Company',
    "BJ's Wholesale Club",
    'The Black & Decker Corporation',
    'Black Hills Corporation',
    'BMC Software',
    'The Boeing Company',
    'Boise Cascade Corporation',
    'Borders Group',
    'BorgWarner',
    'Boston Scientific Corporation',
    'Bowater',
    'Briggs & Stratton Corporation',
    'Brightpoint',
    'Brinker International',
    'Bristol-Myers Squibb Company',
    'Broadwing',
    'Brown Shoe Company',
    'Brown-Forman Corporation',
    'Brunswick Corporation',
    'Budget Group',
    'Burlington Coat Factory Warehouse Corporation',,
    'C. H. Robinson Worldwide',
    'Cablevision Systems Corp',
    'Cabot Corp',
    'Cadence Design Systems',
    'Calpine Corp',
    'Campbell Soup Co',
    'Capital One Financial Corp',
    'Cardinal Health',
    'Caremark Rx',
    'Carlisle Cos.',
    'Carpenter Technology Corp',
    "Casey's General Stores.",
    'Caterpillar',
    'CDW Computer Centers',
    'CellStar Corp',
    'Cendant Corp',
    'Cenex Harvest States Cooperatives',
    'Centex Corp',
    'CenturyTel',
    'Ceridian Corp',
    'CH2M Hill Cos. Ltd',
    'Champion Enterprises',
    'Charles Schwab Corp',
    'Charming Shoppes',
    'Charter Communications',
    'Charter One Financial',
    'ChevronTexaco Corp',
    'Chiquita Brands International',
    'Chubb Corp',
    'Ciena Corp',
    'Cigna Corp',
    'Cincinnati Financial Corp',
    'Cinergy Corp',
    'Cintas Corp',
    'Circuit City Stores',
    'Cisco Systems',
    'Citigroup,',
    'Citizens Communications Co',
    'CKE Restaurants',
    'Clear Channel Communications',
    'The Clorox Co',
    'Coca-Cola Enterprises',
    'Colgate-Palmolive Co',
    'Collins & Aikman Corp',
    'Comcast Corp',
    'Comdisco',
    'Comerica',
    'Comfort Systems USA',
    'Commercial Metals Co',
    'Community Health Systems',
    'Compass Bancshares',
    'Computer Associates International',
    'Computer Sciences Corp',
    'Compuware Corp',
    'Comverse Technology',
    'ConAgra Foods',
    'Concord EFS',
    'Conectiv,',
    'Conoco',
    'Conseco',
    'Consolidated Freightways Corp',
    'Consolidated Edison',
    'Constellation Brands',
    'Constellation Emergy Group',
    'Continental Airlines',
    'Convergys Corp',
    'Cooper Cameron Corp',
    'Cooper Industries Ltd',
    'Cooper Tire & Rubber Co',
    'Corn Products International',
    'Corning',
    'Costco Wholesale Corp',
    'Countrywide Credit Industries',
    'Coventry Health Care',
    'Cox Communications',
    'Crane Co',
    'Crompton Corp',
    'Crown Cork & Seal Co.',
    'CSK Auto Corp',
    'CSX Corp',
    'Cummins',
    'CVS Corp',
    'Cytec Industries',
    'D&K Healthcare Resources',
    'D.R. Horton',
    'Dana Corporation',
    'Danaher Corporation',
    'Darden Restaurants',
    'DaVita',
    'Dean Foods Company',
    'Deere & Company',
    'Del Monte Foods Co',
    'Dell Computer Corporation',
    'Delphi Corp',
    'Delta Air Lines',
    'Deluxe Corporation',
    'Dial Corporation',
    "Dillard's.",
    'Dole Food Company',
    'Dollar General Corporation',
    'Dollar Tree Stores',
    "Domino's Pizza",
    'Dow Chemical Company',
    'Dow Jones & Company',
    "Dreyer's Grand Ice Cream",
    'Duke Energy Corp',
    'Dun & Bradstreet',
    'DURA Automotive Systems',
    'DynCorp',
    'Dynegy',
    'E*Trade Group',
    'E.W. Scripps Company',
    'Earthlink',
    'Eastman Chemical Company',
    'Eastman Kodak Company',
    'Eaton Corporation',
    'Echostar Communications Corporation',
    'Ecolab',
    'Edison International',
    'EGL',
    'El Paso Corporation',
    'Electronic Arts',
    'Electronic Data Systems Corp',
    'Eli Lilly and Company',
    'EMC Corporation',
    'Emcor Group',
    'Emerson Electric Co',
    'Encompass Services Corporation',
    'Energizer Holdings',
    'Engelhard Corporation',
    'Enron Corp',
    'Entergy Corporation',
    'Enterprise Products Partners L.P',
    'EOG Resources',
    'Equifax',
    'Equitable Resources',
    'Equity Office Properties Trust',
    'Equity Residential Properties Trust',
    'Estee Lauder Companies',
    'Exelon Corporation',
    'Exide Technologies',
    'Expeditors International of Washington',
    'Express Scripts',
    'ExxonMobil Corporation',
    'Fairchild Semiconductor International',
    'Family Dollar Stores',
    'Farmland Industries',
    'Federated Department Stores',
    'Federal Express Corp',
    'Felcor Lodging Trust',
    'Ferro Corp',
    'Fidelity National Financial',
    'Fifth Third Bancorp',
    'First American Financial Corp',
    'First Data Corp',
    'First National of Nebraska',
    'Fisher Scientific International',
    'FleetBoston Financial Co',
    'Fleetwood Enterprises',
    'Fleming Companies',
    'Flowers Foods',
    'Flowserv Corp',
    'Fluor Corp',
    'Foamex International',
    'Foot Locker',
    'Footstar',
    'Ford Motor Co',
    'Forest Laboratories',
    'Fortune Brands',
    'Foster Wheeler Ltd',
    'FPL Group',
    'Franklin Resources',
    'Freeport McMoran Copper & Gold',
    'Frontier Oil Corp',
    'Furniture Brands International',
    'Gannett Co',
    'Gap',
    'Gateway',
    'GATX Corporation',
    'Gemstar-TV Guide International',
    'GenCorp',
    'General Cable Corporation',
    'General Dynamics Corporation',
    'General Electric Company',
    'General Mills',
    'General Motors Corporation',
    'Genesis Health Ventures',
    'Gentek',
    'Gentiva Health Services',
    'Genuine Parts Company',
    'Genuity',
    'Genzyme Corporation',
    'Georgia Gulf Corporation',
    'Georgia-Pacific Corporation',
    'Gillette Company',
    'Gold Kist',
    'Golden State Bancorp',
    'Golden West Financial Corporation',
    'Goldman Sachs Group',
    'Goodrich Corporation',
    'The Goodyear Tire & Rubber Company',
    'Granite Construction',
    'Graybar Electric Company',
    'Great Lakes Chemical Corporation',
    'Great Plains Energy',
    'GreenPoint Financial Corp',
    'Greif Bros. Corporation',
    'Grey Global Group',
    'Group 1 Automotive',
    'Guidant Corporation',
    'H&R Block',
    'H.B. Fuller Company',
    'H.J. Heinz Company',
    'Halliburton Co',
    'Harley-Davidson',
    'Harman International Industries',
    "Harrah's Entertainment.",
    'Harris Corp',
    'Harsco Corp',
    'Hartford Financial Services Group',
    'Hasbro',
    'Hawaiian Electric Industries',
    'HCA',
    'Health Management Associates',
    'Health Net',
    'Healthsouth Corp',
    'Henry Schein',
    'Hercules',
    'Herman Miller',
    'Hershey Foods Corp',
    'Hewlett-Packard Company',
    'Hibernia Corp',
    'Hillenbrand Industries',
    'Hilton Hotels Corp',
    'Hollywood Entertainment Corp',
    'Home Depot',
    'Honeywell International',
    'Hormel Foods Corp',
    'Host Marriott Corp',
    'Household International Corp',
    'Hovnanian Enterprises',
    'Hub Group',
    'Hubbell',
    'Hughes Supply',
    'Humana',
    'Huntington Bancshares',
    'Idacorp',
    'IDT Corporation',
    'IKON Office Solutions',
    'Illinois Tool Works',
    'IMC Global',
    'Imperial Sugar Company',
    'IMS Health',
    'Ingles Market',
    'Ingram Micro',
    'Insight Enterprises',
    'Integrated Electrical Services',
    'Intel Corporation',
    'International Paper Co',
    'Interpublic Group of Companies',
    'Interstate Bakeries Corporation',
    'International Business Machines Corp',
    'International Flavors & Fragrances',
    'International Multifoods Corporation',
    'Intuit',
    'IT Group',
    'ITT Industries',
    'Ivax Corp',
    'J.B. Hunt Transport Services',
    'J.C. Penny Co',
    'J.P. Morgan Chase & Co',
    'Jabil Circuit',
    'Jack In The Box',
    'Jacobs Engineering Group',
    'JDS Uniphase Corp',
    'Jefferson-Pilot Co',
    'John Hancock Financial Services',
    'Johnson & Johnson',
    'Johnson Controls',
    'Jones Apparel Group',
    'KB Home',
    'Kellogg Company',
    'Kelly Services',
    'Kemet Corp',
    'KeyCorp',
    'KeySpan Corp',
    'Kimball International',
    'Kimberly-Clark Corporation',
    'Kindred Healthcare',
    'KLA-Tencor Corporation',
    'K-Mart Corp',
    'Knight-Ridder',
    "Kohl's Corp.",
    'KPMG Consulting',
    'Kroger Co',
    'L-3 Communications Holdings',
    'Laboratory Corporation of America Holdings',
    'Lam Research Corporation',
    'LandAmerica Financial Group',
    "Lands' End.",
    'Landstar System',
    'La-Z-Boy',
    'Lear Corporation',
    'Legg Mason',
    'Leggett & Platt',
    'Lehman Brothers Holdings',
    'Lennar Corporation',
    'Lennox International',
    'Level 3 Communications',
    'Levi Strauss & Co',
    'Lexmark International',
    'Limited',
    'Lincoln National Corporation',
    "Linens 'n Things.",
    'Lithia Motors',
    'Liz Claiborne',
    'Lockheed Martin Corporation',
    'Loews Corporation',
    'Longs Drug Stores Corporation',
    'Louisiana-Pacific Corporation',
    "Lowe's Companies.",
    'LSI Logic Corporation',
    'The LTV Corporation',
    'The Lubrizol Corporation',
    'Lucent Technologies',
    'Lyondell Chemical Company',
    'M & T Bank Corporation',
    'Magellan Health Services',
    'Mail-Well',
    'Mandalay Resort Group',
    'Manor Care',
    'Manpower',
    'Marathon Oil Corporation',
    'Mariner Health Care',
    'Markel Corporation',
    'Marriott International',
    'Marsh Supermarkets',
    'Marshall & Ilsley Corporation',
    'Martin Marietta Materials',
    'Maxim',
    'Maytag Corporation',
    "McDonald's Corporation",
    'Medtronic',
    'Mellon Financial Corporation',
    "The Men's Wearhouse.",
    'Merck & Co',
    'Mercury General Corporation',
    'Merrill Lynch & Co.',
    'Metaldyne Corporation',
    'Metals USA',
    'MetLife',
    'Metris Companies',
    'MGIC Investment Corporation',
    'MGM Mirage',
    'Michaels Stores',
    'Micron Technology',
    'Microsoft Corporation',
    'Milacron',
    'Millennium Chemicals',
    'Mirant Corporation',
    'Mohawk Industries',
    'MoistCo!',
    'Molex',
    'The MONY Group',
    'Morgan Stanley Dean Witter & Co',
    'Motorola',
    'MPS Group',
    'Murphy Oil Corporation',
    'Nabors Industries',
    'Nacco Industries',
    'Nash Finch Company',
    'National City Corp',
    'National Commerce Financial Corporation',
    'National Fuel Gas Company',
    'National Oilwell',
    'National Rural Utilities Cooperative Finance Corporation',
    'National Semiconductor Corporation',
    'National Service Industries',
    'Navistar International Corporation',
    'NCR Corporation',
    'The Neiman Marcus Group',
    'New Jersey Resources Corporation',
    'New York Times Company',
    'Newell Rubbermaid',
    'Newmont Mining Corporation',
    'Nextel Communications',
    'Nicor',
    'Nike',
    'NiSource',
    'Noble Energy',
    'Nordstrom',
    'Norfolk Southern Corporation',
    'Nortek',
    'North Fork Bancorporation',
    'Northeast Utilities System',
    'Northern Trust Corporation',
    'Northrop Grumman Corporation',
    'NorthWestern Corporation',
    'Novellus Systems',
    'NSTAR',
    'NTL',
    'Nucor Corp',
    'Nvidia Corp',
    'NVR',
    'Northwest Airlines Corp',
    'Occidental Petroleum Corp',
    'Ocean Energy',
    'Office Depot',
    'OfficeMax',
    'OGE Energy Corp',
    'Oglethorpe Power Corp',
    'Ohio Casualty Corp',
    'Old Republic International Corp',
    'Olin Corp',
    'OM Group',
    'Omnicare',
    'Omnicom Group',
    'On Semiconductor Corp',
    'ONEOK',
    'Oracle Corp',
    'Oshkosh Truck Corp',
    'Outback Steakhouse',
    'Owens & Minor',
    'Owens Corning',
    'Owens-Illinois',
    'Oxford Health Plans',
    'Paccar',
    'PacifiCare Health Systems',
    'Packaging Corp. of America',
    'Pactiv Corp',
    'Pall Corp',
    'Pantry',
    'Park Place Entertainment Corp',
    'Parker Hannifin Corp',
    'Pathmark Stores',
    'Paychex',
    'Payless Shoesource',
    'Penn Traffic Co',
    'Pennzoil-Quaker State Company',
    'Pentair',
    'Peoples Energy Corp',
    'PeopleSoft',
    'Pep Boys Manny, Moe & Jack',
    'Potomac Electric Power Co',
    'Pepsi Bottling Group',
    'PepsiAmericas',
    'PepsiCo',
    'Performance Food Group Co',
    'Perini Corp',
    'PerkinElmer',
    'Perot Systems Corp',
    'Petco Animal Supplies',
    "Peter Kiewit Sons'",
    'PETsMART',
    'Pfizer',
    'Pacific Gas & Electric Corp',
    'Pharmacia Corp',
    'Phar Mor',
    'Phelps Dodge Corp',
    'Philip Morris Companies',
    'Phillips Petroleum Co',
    'Phillips Van Heusen Corp',
    'Phoenix Companies',
    'Pier 1 Imports',
    "Pilgrim's Pride Corporation",
    'Pinnacle West Capital Corp',
    'Pioneer-Standard Electronics',
    'Pitney Bowes',
    'Pittston Brinks Group',
    'Plains All American Pipeline LP',
    'PNC Financial Services Group',
    'PNM Resources',
    'Polaris Industries',
    'Polo Ralph Lauren Corp',
    'PolyOne Corp',
    'Popular',
    'Potlatch Corp',
    'PPG Industries',
    'PPL Corp',
    'Praxair',
    'Precision Castparts Corp',
    'Premcor',
    'Pride International',
    'Primedia',
    'Principal Financial Group',
    'Procter & Gamble Co',
    'Progress Energy',
    'Progressive Corporation',
    'Protective Life Corp',
    'Prudential Financial',
    'PSS World Medical',
    'Public Service Enterprise Group',
    'Publix Super Markets',
    'Puget Energy',
    'Pulte Homes',
    'Qualcomm',
    'Quanta Services',
    'Quantum Corp',
    'Quest Diagnostics',
    'Questar Corp',
    'Quintiles Transnational',
    'Qwest Communications Intl',
    'R.J. Reynolds Tobacco Company',
    'Radio Shack Corporation',
    'Raymond James Financial',
    'Raytheon Company',
    "Reader's Digest Association.",
    'Reebok International Ltd',
    'Regions Financial Corp',
    'Regis Corporation',
    'Reliance Steel & Aluminum Co',
    'Reliant Energy',
    'Rent A Center',
    'Republic Services',
    'Revlon',
    'RGS Energy Group',
    'Rite Aid Corp',
    'Riverwood Holding',
    'RoadwayCorp',
    'Robert Half International',
    'Rock-Tenn Co',
    'Rockwell Automation',
    'Rohm & Haas Co',
    'Ross Stores',
    'RPM',
    'Ruddick Corp',
    'Ryder System',
    'Ryerson Tull',
    'Ryland Group',
    'Sabre Holdings Corp',
    'Safeco Corp',
    'Safeguard Scientifics',
    'Safeway',
    'Saks',
    'Sanmina-SCI',
    'Sara Lee Corp',
    'SBC Communications',
    'Scana Corp',
    'Schering-Plough Corp',
    'Scholastic Corp',
    'Science Applications Intl.',
    'Scientific-Atlanta',
    'Scotts Company',
    'Seaboard Corp',
    'Sealed Air Corp',
    'Sears Roebuck & Co',
    'Sempra Energy',
    'Sequa Corp',
    'Service Corp. International',
    'ServiceMaster Co',
    'Shaw Group',
    'Sherwin-Williams Company',
    'Shopko Stores',
    'Siebel Systems',
    'Sierra Health Services',
    'Sierra Pacific Resources',
    'Silgan Holdings',
    'Silicon Graphics',
    'Simon Property Group',
    'SLM Corporation',
    'Smith International',
    'Smithfield Foods',
    'Smurfit-Stone Container Corp',
    'Snap-On',
    'Solectron Corp',
    'Solutia',
    'Sonic Automotive',
    'Sonoco Products Co',
    'Southern Company',
    'Southern Union Company',
    'SouthTrust Corp',
    'Southwest Airlines Co',
    'Southwest Gas Corp',
    'Sovereign Bancorp',
    'Spartan Stores',
    'Spherion Corp',
    'Sports Authority',
    'Sprint Corp',
    'SPX Corp',
    'St. Jude Medical',
    'Staff Leasing',
    'StanCorp Financial Group',
    'Standard Pacific Corp',
    'Stanley Works',
    'Staples',
    'Starbucks Corp',
    'Starwood Hotels & Resorts Worldwide',
    'State Street Corp',
    'Stater Bros. Holdings',
    'Steelcase',
    'Stein Mart',
    'Stilwell Financial',
    'Storage Technology Corporation',
    'Stryker Corp',
    'Sun Healthcare Group',
    'Sun Microsystems',
    'SunGard Data Systems',
    'Sunoco',
    'SunTrust Banks',
    'Supervalu',
    'Symbol Technologies',
    'Sysco Corp',
    'Systemax',
    'Target Corp',
    'Tech Data Corporation',
    'TECO Energy',
    'Tektronix',
    'Teleflex',
    'Telephone & Data Systems',
    'Tenet Healthcare Corporation',
    'Tenneco Automotive',
    'Teradyne',
    'Tesoro Petroleum Corp',
    'Texas Instruments',
    'Textron',
    'Thermo Electron Corporation',
    'Tiffany & Co',
    'Torchmark Corporation',
    'Tower Automotive',
    "Toys 'R' Us",
    'Trans World Entertainment Corp',
    'TravelCenters of America',
    'Triad Hospitals',
    'Trigon Healthcare',
    'Trump Hotels & Casino Resorts',
    'Tyson Foods',
    'Unified Western Grocers',
    'Union Planters Corp',
    'Unisource Energy Corp',
    'Unisys Corporation',
    'United Auto Group',
    'United Defense Industries',
    'United Parcel Service',
    'United Rentals',
    'United Stationers',
    'United Technologies Corporation',
    'UnitedHealth Group',
    'Unitrin',
    'Universal Corporation',
    'Universal Forest Products',
    'Universal Health Services',
    'Unocal Corporation',
    'Unova',
    'UnumProvident Corporation',
    'URS Corporation',
    'US Airways Group',
    'US Oncology',
    'USA Interactive',
    'USFreighways Corporation',
    'USG Corporation',
    'UST',
    'Valero Energy Corporation',
    'Valspar Corporation',
    'Value City Department Stores',
    'Varco International',
    'Vectren Corporation',
    'Veritas Software Corporation',
    'Verizon Communications',
    'VF Corporation',
    'Viacom',
    'Viad Corp',
    'Viasystems Group',
    'Vishay Intertechnology',
    'Visteon Corporation',
    'Volt Information Sciences',
    'Vulcan Materials Company',
    'W.R. Berkley Corporation',
    'W.R. Grace & Co',
    'W.W. Grainger',
    'Wachovia Corporation',
    'Wakenhut Corporation',
    'Walgreen Co',
    'Wallace Computer Services',
    'Wal-Mart Stores',
    'Walt Disney Co',
    'Walter Industries',
    'Washington Mutual',
    'Washington Post Co',
    'Waste Management',
    'Watsco',
    'Weatherford International',
    'Weis Markets',
    'Wellpoint Health Networks',
    'Wells Fargo & Company',
    "Wendy's International",
    'Werner Enterprises',
    'WESCO International',
    'Western Digital',
    'Western Gas Resources',
    'Whirlpool Corporation',
    'Whole Foods Market',
    'Williams Sonoma',
    'Winn Dixie Stores',
    'Wisconsin Energy Corporation',
    'Wm Wrigley Jr Company',
    'World Fuel Services Corporation',
    'WorldCom',
    'Worthington Industries',
    'WPS Resources Corporation',
    'Wyeth',
    'Wyndham International',
    'Xcel Energy',
    'Xerox Corp',
    'Xilinx',
    'XO Communications',
    'Yellow Corporation',
    'York International Corp',
    'Yum Brands',
    'Zale Corporation',
    'Zions Bancorporation',
    'BookBub',
    'Kesher Afterschool',
    'MassDOT',
    'MBTA',
    'Voltus',
    'Weyland-Yutani Corporation',
    'Umbrella Corporation',
    'Soylent Corporation',
    'Cyberdyne Systems',
    'InGen',
    'Initech',
    'Buy n Large',
    'KardashianPutin Global Enterprises',
    'Yeezy Inc',
    'Wonka Industries',
    'Monsters, Inc',
    'Krusty Krab',
    'Los Pollos Hermanos',
    'Bluth Company',
    'MOM Corp'
];
