export default [
    'Accountant',
    'Televangelist',
    'Award show awards engraver',
    'Auditor',
    'Actor',
    'Tender'
    'Adult Basic, Secondary, and Tertiary Education and Literacy and Illiteracy Teacher',
    'Secret Agent',
    'Business Managers of Artist',
    'Agricultural Worker',
    'Food Science Technician and Professional Taster',
    'Air Traffic Controller',
    'Airplane',
    'Airline Pilot',
    'All Occupations',
    'Ambulance Driver',
    'Ferris Wheel Operator',
    'Anesthesiologist',
    'Animal Breeder',
    'Animal Trainer',
    'Archeologist',
    'Assessors of Real Estate',
    'Architect',
    'Artist',
    'Astronomer',
    'Astrologer',
    'Athlete',
    'Sports Competitor',
    'Atmospheric and Space Scientist',
    'Atmospheric Music Evangelist',
    'Audio-Visual and Multimedia Collections Specialist',
    'Mechanic',
    'Bellhop',
    'Bailiff',
    'Baker',
    'Chandler AKA Candlestick Maker',
    'Weaver',
    'Rare book collector',
    'Barber',
    'Bartender',
    'Bicycle Repairer',
    'Biophysicist',
    'Biological Science Teacher',
    'Bridge and Lock Tender',
    'Broadcast News Analyst',
    'Budget Analyst',
    'Building Cleaning Worker',
    'Bus Driver',
    'Budding Activist',
    'Busines',
    'Butcher',
    'Meat Cutter',
    'Buyer',
    'Cabinetmaker',
    'Captain',
    'Carpenter',
    'Carpet Installer',
    'Cartographer',
    'Photogrammetrist',
    'Cashier',
    'Chef',
    'Head Cook',
    'Chief Executive of Business',
    'Child of CEO',
    'Child',
    'Chiropractor',
    'Choreographer',
    'Cleaners of Vehicle',
    'Equipment Failure Expert',
    'Coachella Specialist',
    'Coil Winder',
    'Coin Collector',
    'Combined Food Preparation and Serving Worker',
    'Computer Numerically Controlled Machine Tool Programmer',
    'Computer Programmer',
    'Computer',
    'Concierge',
    'Conservation Scientist',
    'Repairer, Fixer, and Solver',
    'Correctional Officer',
    'Jailer',
    'Cost Estimator',
    'Costume Attendant',
    'Counselor',
    'Courier',
    'Pigeon Message Attendant',
    'Court Reporter',
    'Crossing Guard',
    'Cutting and Slicing Machine Setter',
    'Dancer',
    'Demonstrator',
    'Counter Protester',
    'Fake News Fact Checker',
    'Product Promoter',
    'Dental Hygienist',
    'Dentist',
    'Detective',
    'Criminal Investigator',
    'Diagnostic Medical Sonographer',
    'Nutritionist',
    'Dining Room and Cafeteria Attendant',
    'Bartender Helper Assistant',
    'Door-to-Door Sales Worker',
    'Earth Driller',
    'Economist',
    'Educational Teacher',
    'Electrician',
    'Eligibility Interviewer',
    'Embalmer',
    'Paramedic',
    'The person at the hospital who rolls their eyes when asked any question',
    'Engineer',
    'English Language and Literature Teacher',
    'Entertainer',
    'Performer',
    'Entertainment Attendant',
    'Specialist',
    'Epidemiologist',
    "Can't say due to NDA",
    'Engraver',
    'Explosives Worker',
    'Fabric Mender',
    'Faller',
    'Farmer',
    'Laborer',
    'Farmworker',
    'Fashion Designer',
    'Fence Erector',
    'Financial Examiner',
    'Fish and Game Warden',
    'Aerobics Instructor',
    'Flight Attendant',
    'Food and Tobacco Roasting',
    'Forest Fire Inspector',
    'Prevention Specialist',
    'Funeral Attendant',
    'Furniture Finisher',
    'Gaming Cage Worker',
    'Gaming Surveillance Officer',
    'Gaming and Sports Book Writer',
    'Runner',
    'Sorter',
    'Grinding',
    'Hairdresser',
    'Historian',
    'Home Health Aide',
    'Hunter',
    'Military Industrial-Organizational Psychologist',
    'Senior Intern',
    'Janitor',
    'Judge Judy',
    'Lawyer',
    'Librarian',
    'Lifeguard',
    'Loan Interviewer',
    'Maid',
    'Mail Clerk',
    'Makeup Artist',
    'TikTok Influencer',
    'Pedicurist',
    'Marriage and Family Therapist',
    'Massage Therapist',
    'Mathematician',
    'Mechanical Door Repairer',
    'Medical Secretary',
    'Meter Reader',
    'Middle School Teacher',
    'Mine Shuttle Car Operator',
    'Musical Instrument Repairer',
    'Musician',
    'Singer',
    'Nonfarm Animal Caretaker',
    'Nuclear Bomb Engineer',
    'Gynecologist',
    'Optometrist',
    'Oral and Maxillofacial Surgeon',
    'Paralegal',
    'Parking Enforcement Worker',
    'Parking Lot Attendant',
    'Pediatrician',
    'Pharmacist',
    'Philosophy and Religion Teacher',
    'Philosopher',
    'Photographer',
    'Physician',
    'Surgeon',
    'Physicist',
    'Plumber',
    'Person who stands behind public figure at press conference',
    'Podiatrist',
    "Police and Sheriff's Patrol Officer",
    'Postal Service Mail Sorter',
    'Preschool Teacher',
    'Juice Presser',
    'Owner, CEO, and Founder',
    'College roommate of CEO and Founder',
    'Beyonce',
    'Psychiatrist',
    'Radio and Television Announcer',
    'Registered Nurse',
    'Religious Worker',
    'Reporter',
    'Rock Splitter',
    'Sailor',
    'Marine Oiler',
    'Sales Engineer',
    'Secretary',
    'Administrative Assistant',
    'Security Guard',
    'Sex Worker',
    'Shampooer',
    'Skincare Specialist',
    'Slaughterer',
    'Meat Packer',
    'Social Worker',
    'Software Developer',
    'Soil and Plant Scientist',
    'Special Education Teacher',
    'Stationary Engineer',
    'Statistician',
    'Order Filler',
    'Tax Examiner',
    'Taxi Driver',
    'Telemarketer',
    'Telephone Operator',
    'Teller',
    'Terrazzo Worker',
    'Tour Guide',
    'Escort',
    'Umpire',
    'Urban and Regional Planner',
    'Veterinarian',
    'Laboratory Animal Caretaker',
    'Waiter',
    'Watch Repairer',
    'Welder',
    'Word Processor',
    'Writer',
    'Author',
    'Zoologist',
    'Wildlife Biologist',
    'Presidential Monument Designer',
    'Responsible Adult',
    'Asker of Questions',
    'Unemployed",
    '#GirlDad', 
    'Whistleblower',
    'Corporate Spy',
    'Daddy',
    'Gravedigger',
    'Brewer',
    'Quiet Quitter',
    'Sock Darner',
    'Vegan',
    'Street corner fundraiser who does NOT ignore you if you have headphones in',
    'Copyright Law Infringer',
    'Patent Troll',
    'Fantasy Nerd', 
    'Dungeon Master',
    'Sandwich Artist',
    'Snow Cone Technician',
    'Game Stonks Ape',
];
