export default [
    'I know the best spot in town for ',
    'I get along best with people ',
    'My role in the friend group ',
    'I want someone who ',
    'I’m convinced that ',
    "Don't hate me if ",
    'A life goal of mine ',
    'I geek out on ',
    'I flip out over ',
    'I’m weirdly attracted to ',
    'A social cause I care about ',
    'Favorite holiday tradition ',
    'I’m overly competitive about ',
    'I’m actually legitimately bad at ',
    'Worst fad I participated in ',
    'The award I should be nominated for ',
    'Next vacation spot ',
    'I spend most of my money on ',
    'My most irrational fear ',
    'One thing I’ll never do again ',
    'Weirdest gift I have given or received ',
    'My ideal fake sick day ',
    'My happy place ',
    "I'll know it's time to delete this app when ",
    'This year I really want to '
];
